# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-20 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
