# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-20 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vin', '0002_project_github_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='deployed_link',
        ),
    ]
